
// Interromper imediatamente quando ocorrer um erro 
\set ON_ERROR_STOP on
SET client_min_messages = warning;
SET search_path TO public;


/* =============================================================================
   3. DOMÍNIOS E TIPOS PERSONALIZADOS
   ============================================================================= */
-- vinculo_t: tipo citado no modelo (pre_requisito.vinculo) sem definição.
-- Domínio sem restrição de valores até que o modelo informe o conjunto
-- permitido (ver A4). Quando definido, adicionar:
--   ALTER DOMAIN vinculo_t ADD CONSTRAINT ck_vinculo_t CHECK (VALUE IN (...));
CREATE DOMAIN vinculo_t AS text;


/* =============================================================================
   4. CRIAÇÃO DAS TABELAS (colunas e obrigatoriedade; PK/FK/UNIQUE em 5-7)
   Ordem alfabética: dependências são resolvidas porque as FKs só são criadas
   na seção 6.
   ============================================================================= */

CREATE TABLE pais (
    id_pais      integer GENERATED BY DEFAULT AS IDENTITY,
    codigo_pais  integer,
    nome_pais    varchar(100)
);

CREATE TABLE estado (
    id_estado    integer GENERATED BY DEFAULT AS IDENTITY,
    id_pais      integer,
    nome_estado  varchar(100),
    municipio    varchar(100)          -- preservado conforme o modelo
);

CREATE TABLE cidade (
    id_cidade      integer GENERATED BY DEFAULT AS IDENTITY,
    nome           varchar(100),
    codigo_cidade  integer,
    id_estado      integer
);

CREATE TABLE campus (
    id_campus     smallint GENERATED BY DEFAULT AS IDENTITY,
    nome_campus   varchar(60),
    cep           varchar(9),          -- nvarchar(9) no modelo (A1)
    endereco      varchar(100),
    telefone      varchar(15),
    complementos  varchar(100),
    qtd_blocos    smallint,
    salas         smallint
);

CREATE TABLE predio (
    id_predio    smallint GENERATED BY DEFAULT AS IDENTITY,
    id_cidade    integer,
    qtd_predios  integer,
    id_campus    smallint
);

CREATE TABLE bloco (
    id_bloco   smallint GENERATED BY DEFAULT AS IDENTITY,
    id_predio  smallint
);

CREATE TABLE sala (
    id_sala     integer GENERATED BY DEFAULT AS IDENTITY,
    codigo      varchar(10),
    capacidade  smallint,
    tipo        varchar(30),
    id_bloco    smallint
);

CREATE TABLE curso (
    id_curso   smallint GENERATED BY DEFAULT AS IDENTITY,
    id_campus  smallint,
    codigo     varchar(10),
    nome       varchar(120),
    grau       varchar(120),
    ch_total   smallint
);

CREATE TABLE curriculo (
    id_curriculo  smallint GENERATED BY DEFAULT AS IDENTITY,
    ano_vigencia  smallint,
    ativo         boolean,
    id_curso      smallint
);

CREATE TABLE disciplina (
    id_disciplina  integer GENERATED BY DEFAULT AS IDENTITY,
    codigo         varchar(10),
    nome           varchar(120),
    ch_teorica     smallint,
    ch_pratica     smallint,
    ch_total       smallint,
    ementa         text
);

CREATE TABLE curriculo_disciplina (
    id_curriculo   smallint NOT NULL,   -- PK/FK
    id_disciplina  integer  NOT NULL,   -- PK/FK
    periodo        smallint,
    tipo           varchar(20)
);

CREATE TABLE pre_requisito (
    id_disciplina  integer NOT NULL,    -- PK/FK
    id_requisito   integer NOT NULL,    -- PK/FK
    vinculo        vinculo_t
);

CREATE TABLE periodo_letivo (
    id_periodo_letivo  smallint GENERATED BY DEFAULT AS IDENTITY,
    ano                smallint,
    semestre           smallint,
    data_inicio        date,
    data_fim           date
);

CREATE TABLE professor (
    id_professor  integer GENERATED BY DEFAULT AS IDENTITY,
    matricula     varchar(12),          -- U
    nome          varchar(120),
    email         varchar(120),
    titulacao     varchar(20)
);

CREATE TABLE turma (
    id_turma           integer GENERATED BY DEFAULT AS IDENTITY,
    id_disciplina      integer,
    id_professor       integer,
    id_periodo_letivo  smallint,
    turno              varchar(10),
    codigo             varchar(15)
);

CREATE TABLE aluno (
    id_aluno      integer GENERATED BY DEFAULT AS IDENTITY,
    id_curriculo  smallint,
    nome          varchar(120),
    cpf           char(11),
    email         varchar(120),         -- U
    nascimento    date
);

CREATE TABLE matricula (
    id_matricula    integer GENERATED BY DEFAULT AS IDENTITY,
    id_aluno        integer NOT NULL,   -- FK/U (A5)
    id_turma        integer NOT NULL,   -- FK/U (A5)
    data_matricula  date,
    status          varchar(15)
);

CREATE TABLE historico (
    id_historico  integer GENERATED BY DEFAULT AS IDENTITY,
    id_matricula  integer NOT NULL,     -- 1:1 obrigatório (A6)
    n1            numeric,              -- A2, A13
    n2            numeric,
    n3            numeric,
    media_final   numeric,
    frequencia    numeric,
    situacao      varchar(15)
);

CREATE TABLE log_matricula (
    id_log         bigint GENERATED BY DEFAULT AS IDENTITY,
    id_matricula   integer,
    acao           varchar(20),
    ocorrido_em    timestamp,
    usuario        varchar(60),
    detalhe        text
);

CREATE TABLE feriado (
    id_feriado  integer GENERATED BY DEFAULT AS IDENTITY,
    data        date,
    descricao   varchar(120)
);

CREATE TABLE pais_feriado (             -- entidade associativa N:N
    fk_id_pais     integer NOT NULL,    -- PFK
    fk_id_feriado  integer NOT NULL     -- PFK (tipo inferido, A3)
);


/* =============================================================================
   5. CHAVES PRIMÁRIAS
   ============================================================================= */
ALTER TABLE pais                 ADD CONSTRAINT pk_pais                 PRIMARY KEY (id_pais);
ALTER TABLE estado               ADD CONSTRAINT pk_estado               PRIMARY KEY (id_estado);
ALTER TABLE cidade               ADD CONSTRAINT pk_cidade               PRIMARY KEY (id_cidade);
ALTER TABLE campus               ADD CONSTRAINT pk_campus               PRIMARY KEY (id_campus);
ALTER TABLE predio               ADD CONSTRAINT pk_predio               PRIMARY KEY (id_predio);
ALTER TABLE bloco                ADD CONSTRAINT pk_bloco                PRIMARY KEY (id_bloco);
ALTER TABLE sala                 ADD CONSTRAINT pk_sala                 PRIMARY KEY (id_sala);
ALTER TABLE curso                ADD CONSTRAINT pk_curso                PRIMARY KEY (id_curso);
ALTER TABLE curriculo            ADD CONSTRAINT pk_curriculo            PRIMARY KEY (id_curriculo);
ALTER TABLE disciplina           ADD CONSTRAINT pk_disciplina           PRIMARY KEY (id_disciplina);
ALTER TABLE curriculo_disciplina ADD CONSTRAINT pk_curriculo_disciplina PRIMARY KEY (id_curriculo, id_disciplina);
ALTER TABLE pre_requisito        ADD CONSTRAINT pk_pre_requisito        PRIMARY KEY (id_disciplina, id_requisito);
ALTER TABLE periodo_letivo       ADD CONSTRAINT pk_periodo_letivo       PRIMARY KEY (id_periodo_letivo);
ALTER TABLE professor            ADD CONSTRAINT pk_professor            PRIMARY KEY (id_professor);
ALTER TABLE turma                ADD CONSTRAINT pk_turma                PRIMARY KEY (id_turma);
ALTER TABLE aluno                ADD CONSTRAINT pk_aluno                PRIMARY KEY (id_aluno);
ALTER TABLE matricula            ADD CONSTRAINT pk_matricula            PRIMARY KEY (id_matricula);
ALTER TABLE historico            ADD CONSTRAINT pk_historico            PRIMARY KEY (id_historico);
ALTER TABLE log_matricula        ADD CONSTRAINT pk_log_matricula        PRIMARY KEY (id_log);
ALTER TABLE feriado              ADD CONSTRAINT pk_feriado              PRIMARY KEY (id_feriado);
ALTER TABLE pais_feriado         ADD CONSTRAINT pk_pais_feriado         PRIMARY KEY (fk_id_pais, fk_id_feriado);


/* =============================================================================
   6. CHAVES ESTRANGEIRAS (sem ON DELETE/ON UPDATE: não definidos no modelo, A11)
   ============================================================================= */
-- Geografia
ALTER TABLE estado ADD CONSTRAINT fk_estado_pais   FOREIGN KEY (id_pais)   REFERENCES pais (id_pais);
ALTER TABLE cidade ADD CONSTRAINT fk_cidade_estado FOREIGN KEY (id_estado) REFERENCES estado (id_estado);
-- Infraestrutura
ALTER TABLE predio ADD CONSTRAINT fk_predio_cidade FOREIGN KEY (id_cidade) REFERENCES cidade (id_cidade);   -- A7
ALTER TABLE predio ADD CONSTRAINT fk_predio_campus FOREIGN KEY (id_campus) REFERENCES campus (id_campus);
ALTER TABLE bloco  ADD CONSTRAINT fk_bloco_predio  FOREIGN KEY (id_predio) REFERENCES predio (id_predio);
ALTER TABLE sala   ADD CONSTRAINT fk_sala_bloco    FOREIGN KEY (id_bloco)  REFERENCES bloco (id_bloco);
-- Estrutura curricular
ALTER TABLE curso     ADD CONSTRAINT fk_curso_campus     FOREIGN KEY (id_campus) REFERENCES campus (id_campus);
ALTER TABLE curriculo ADD CONSTRAINT fk_curriculo_curso  FOREIGN KEY (id_curso)  REFERENCES curso (id_curso);       -- A7
ALTER TABLE curriculo_disciplina ADD CONSTRAINT fk_curdisc_curriculo  FOREIGN KEY (id_curriculo)  REFERENCES curriculo (id_curriculo);
ALTER TABLE curriculo_disciplina ADD CONSTRAINT fk_curdisc_disciplina FOREIGN KEY (id_disciplina) REFERENCES disciplina (id_disciplina);
ALTER TABLE pre_requisito ADD CONSTRAINT fk_prereq_disciplina FOREIGN KEY (id_disciplina) REFERENCES disciplina (id_disciplina);  -- A8
ALTER TABLE pre_requisito ADD CONSTRAINT fk_prereq_requisito  FOREIGN KEY (id_requisito)  REFERENCES disciplina (id_disciplina);  -- A8
-- Oferta
ALTER TABLE turma ADD CONSTRAINT fk_turma_disciplina FOREIGN KEY (id_disciplina)     REFERENCES disciplina (id_disciplina);
ALTER TABLE turma ADD CONSTRAINT fk_turma_professor  FOREIGN KEY (id_professor)      REFERENCES professor (id_professor);
ALTER TABLE turma ADD CONSTRAINT fk_turma_periodo    FOREIGN KEY (id_periodo_letivo) REFERENCES periodo_letivo (id_periodo_letivo);
-- Discentes
ALTER TABLE aluno         ADD CONSTRAINT fk_aluno_curriculo   FOREIGN KEY (id_curriculo) REFERENCES curriculo (id_curriculo);
ALTER TABLE matricula     ADD CONSTRAINT fk_matricula_aluno   FOREIGN KEY (id_aluno)     REFERENCES aluno (id_aluno);
ALTER TABLE matricula     ADD CONSTRAINT fk_matricula_turma   FOREIGN KEY (id_turma)     REFERENCES turma (id_turma);
ALTER TABLE historico     ADD CONSTRAINT fk_historico_matric  FOREIGN KEY (id_matricula) REFERENCES matricula (id_matricula);
ALTER TABLE log_matricula ADD CONSTRAINT fk_log_matricula     FOREIGN KEY (id_matricula) REFERENCES matricula (id_matricula);
-- Calendário (associativa)
ALTER TABLE pais_feriado ADD CONSTRAINT fk_paisferiado_pais    FOREIGN KEY (fk_id_pais)    REFERENCES pais (id_pais);
ALTER TABLE pais_feriado ADD CONSTRAINT fk_paisferiado_feriado FOREIGN KEY (fk_id_feriado) REFERENCES feriado (id_feriado);


/* =============================================================================
   7. DEMAIS RESTRIÇÕES (UNIQUE marcadas com "U" no modelo)
   ============================================================================= */
ALTER TABLE aluno     ADD CONSTRAINT uq_aluno_email            UNIQUE (email);
ALTER TABLE professor ADD CONSTRAINT uq_professor_matricula    UNIQUE (matricula);
ALTER TABLE matricula ADD CONSTRAINT uq_matricula_aluno_turma  UNIQUE (id_aluno, id_turma);   -- A5
ALTER TABLE historico ADD CONSTRAINT uq_historico_matricula    UNIQUE (id_matricula);         -- A6 (1:1)
-- Observação: UNIQUE já cria índice B-tree. Estes 4 índices cobrem também:
--   matricula(id_aluno,...)  -> buscas por aluno
--   historico(id_matricula)  -> FK/joins de histórico


/* =============================================================================
   8. CRIAÇÃO DOS ÍNDICES (justificativas e evidências nas seções 10-11)
   =============================================================================
   Índices JÁ existentes por constraint (não duplicar): todas as PKs, e
   uq_aluno_email, uq_professor_matricula, uq_matricula_aluno_turma,
   uq_historico_matricula.

   NÃO indexados de propósito (tabelas pequenas, seq scan é mais barato e cada
   índice custaria em INSERT/UPDATE/DELETE): estado.id_pais, cidade.id_estado,
   predio.id_cidade/id_campus, bloco.id_predio, sala.id_bloco, curso.id_campus,
   curriculo.id_curso, pais_feriado.fk_id_feriado; também
   curriculo_disciplina/pre_requisito/pais_feriado pela 1ª coluna (cobertas pela
   PK composta) e matricula.id_aluno / historico.id_matricula (cobertos pelos
   UNIQUE). */

-- I1: lista de alunos de uma turma (diário de classe) e checagem da FK ao
--     remover/alterar turma. Coluna líder id_turma (a UNIQUE existente só
--     atende id_aluno na frente). id_aluno incluído permite index-only scan.
CREATE INDEX idx_matricula_turma_aluno
    ON matricula (id_turma, id_aluno);

-- I2: turmas de um professor em um período. Igualdade nas duas colunas;
--     id_professor primeiro (mais seletivo) e ainda serve consultas só por
--     professor.
CREATE INDEX idx_turma_professor_periodo
    ON turma (id_professor, id_periodo_letivo);

-- I3: oferta de uma disciplina em um período (planejamento de matrícula).
CREATE INDEX idx_turma_disciplina_periodo
    ON turma (id_disciplina, id_periodo_letivo);

-- I4: alunos de um currículo (migração/relatórios de currículo). Seletividade
--     moderada (muitos alunos por currículo, mas fração pequena da tabela).
CREATE INDEX idx_aluno_curriculo
    ON aluno (id_curriculo);

-- (Candidato parcial avaliado e DESCARTADO: curriculo(id_curso) WHERE ativo.
--  O planner ignorou o índice na tabela de 120 linhas: sem ganho, só custo. Ver T6.)

-- I5: trilha de auditoria de uma matrícula em ordem cronológica inversa.
--     Tabela append-only e grande; o composto evita sort e atende FK.
CREATE INDEX idx_log_matricula_matricula_ocorrido
    ON log_matricula (id_matricula, ocorrido_em);


/* =============================================================================
   9. CONSULTAS DE VALIDAÇÃO ESTRUTURAL
   ============================================================================= */
-- 9.1 Contagens esperadas: 21 tabelas, 21 PKs, 22 FKs, 4 UNIQUE
SELECT
  (SELECT count(*) FROM information_schema.tables
    WHERE table_schema='public' AND table_type='BASE TABLE')          AS tabelas,   -- esperado 21
  (SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace
    WHERE n.nspname='public' AND c.contype='p')                       AS pks,       -- esperado 21
  (SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace
    WHERE n.nspname='public' AND c.contype='f')                       AS fks,       -- esperado 22
  (SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace
    WHERE n.nspname='public' AND c.contype='u')                       AS uniques;   -- esperado 4

-- 9.2 Tabelas sem chave primária (esperado: nenhuma linha)
SELECT c.relname
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname='public' AND c.relkind='r'
  AND NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conrelid=c.oid AND k.contype='p');

-- 9.3 Relação das FKs (tabela.coluna -> referenciada)
SELECT conrelid::regclass AS tabela, conname,
       pg_get_constraintdef(oid) AS definicao
FROM pg_constraint
WHERE contype='f' AND connamespace='public'::regnamespace
ORDER BY 1, 2;

-- 9.4 Colunas por tabela (conferir com o modelo)
SELECT table_name, count(*) AS colunas
FROM information_schema.columns WHERE table_schema='public'
GROUP BY table_name ORDER BY table_name;

-- 9.5 Índices existentes
SELECT tablename, indexname, indexdef
FROM pg_indexes WHERE schemaname='public' ORDER BY tablename, indexname;

-- 9.6 Domínio criado
SELECT typname, typtype, format_type(typbasetype, NULL) AS base
FROM pg_type WHERE typname='vinculo_t';


/* =============================================================================
   10. CONSULTAS DE ANÁLISE DE DESEMPENHO
   =============================================================================
   Execução: psql -X -d bd_ii_benchmark -f modelo_fisico_postgresql.sql
   (o banco precisa se chamar bd_ii_benchmark e estar vazio).

   Método por índice (ANTES/DEPOIS):
     ANTES : BEGIN; DROP INDEX <idx>; EXPLAIN...; ROLLBACK;  (o DROP é desfeito
             pelo ROLLBACK: o índice permanece; só vale no banco de benchmark)
     DEPOIS: EXPLAIN com o índice presente.
     Cada medição = 1 execução de aquecimento (descartada, \o /dev/null) +
     3 execuções registradas. Os resultados reais foram coletados em execução
     real (ver seção 11).
   ============================================================================= */

-- 10.0 TRAVA DE SEGURANÇA
DO $$
BEGIN
  IF current_database() <> 'bd_ii_benchmark' THEN
    RAISE EXCEPTION 'Seção 10 só pode rodar no banco bd_ii_benchmark (atual: %)', current_database();
  END IF;
  IF EXISTS (SELECT 1 FROM aluno) THEN
    RAISE EXCEPTION 'Dados já carregados; abortando para evitar carga duplicada';
  END IF;
END $$;

-- 10.1 CARGA DE DADOS *SINTÉTICOS* (somente para benchmark; não são dados reais)
SELECT setseed(0.42);

INSERT INTO pais (codigo_pais, nome_pais)
SELECT g, 'Pais '||g FROM generate_series(1,5) g;

INSERT INTO estado (id_pais, nome_estado, municipio)
SELECT 1+(g%5), 'Estado '||g, 'Municipio '||g FROM generate_series(1,30) g;

INSERT INTO cidade (nome, codigo_cidade, id_estado)
SELECT 'Cidade '||g, g, 1+(g%30) FROM generate_series(1,300) g;

INSERT INTO campus (nome_campus, cep, endereco, telefone, complementos, qtd_blocos, salas)
SELECT 'Campus '||g, '70000-000', 'Endereco '||g, '6100000000'||g, 'Compl '||g, 4, 120
FROM generate_series(1,5) g;

INSERT INTO predio (id_cidade, qtd_predios, id_campus)
SELECT 1+(g%300), 1, 1+(g%5) FROM generate_series(1,20) g;

INSERT INTO bloco (id_predio) SELECT 1+(g%20) FROM generate_series(1,60) g;

INSERT INTO sala (codigo, capacidade, tipo, id_bloco)
SELECT 'S'||g, 20+(g%80), (ARRAY['sala','laboratorio','auditorio'])[1+(g%3)], 1+(g%60)
FROM generate_series(1,1200) g;

INSERT INTO curso (id_campus, codigo, nome, grau, ch_total)
SELECT 1+(g%5), 'C'||g, 'Curso '||g, (ARRAY['bacharelado','licenciatura','tecnologo'])[1+(g%3)], 2400+(g%10)*100
FROM generate_series(1,40) g;

INSERT INTO curriculo (ano_vigencia, ativo, id_curso)
SELECT 2010+(g%15), (g%3<>0), 1+(g%40) FROM generate_series(1,120) g;

INSERT INTO disciplina (codigo, nome, ch_teorica, ch_pratica, ch_total, ementa)
SELECT 'D'||g, 'Disciplina '||g, 30+(g%3)*15, 15*(g%3), 30+(g%3)*15+15*(g%3), 'Ementa sintetica '||g
FROM generate_series(1,1000) g;

INSERT INTO curriculo_disciplina (id_curriculo, id_disciplina, periodo, tipo)
SELECT c, ((c*37 + k*23) % 1000)+1, 1+(k/5), (ARRAY['obrigatoria','optativa'])[1+(k%2)]
FROM generate_series(1,120) c, generate_series(0,39) k;

INSERT INTO pre_requisito (id_disciplina, id_requisito, vinculo)
SELECT d, ((d-1 + k*101) % 1000)+1, 'v'||k
FROM generate_series(1,1000) d, generate_series(1,2) k;

INSERT INTO periodo_letivo (ano, semestre, data_inicio, data_fim)
SELECT 2020+((g-1)/2), 1+((g-1)%2),
       make_date(2020+((g-1)/2), CASE WHEN (g-1)%2=0 THEN 2 ELSE 8 END, 1),
       make_date(2020+((g-1)/2), CASE WHEN (g-1)%2=0 THEN 7 ELSE 12 END, 15)
FROM generate_series(1,12) g;

INSERT INTO professor (matricula, nome, email, titulacao)
SELECT 'P'||lpad(g::text,8,'0'), 'Professor '||g, 'prof'||g||'@exemplo.invalid',
       (ARRAY['mestre','doutor','especialista'])[1+(g%3)]
FROM generate_series(1,2000) g;

INSERT INTO turma (id_disciplina, id_professor, id_periodo_letivo, turno, codigo)
SELECT 1+floor(random()*1000)::int, 1+floor(random()*2000)::int, 1+floor(random()*12)::int,
       (ARRAY['manha','tarde','noite'])[1+(g%3)], 'T'||g
FROM generate_series(1,60000) g;

INSERT INTO aluno (id_curriculo, nome, cpf, email, nascimento)
SELECT 1+floor(random()*120)::int, 'Aluno '||g, lpad(g::text,11,'0'),
       'aluno'||g||'@exemplo.invalid', date '1995-01-01' + (g%3650)
FROM generate_series(1,100000) g;

INSERT INTO matricula (id_aluno, id_turma, data_matricula, status)
SELECT a, ((a*7 + k*7919) % 60000)+1, date '2024-02-01' + (a%60),
       (ARRAY['s1','s2','s3'])[1+(k%3)]
FROM generate_series(1,100000) a, generate_series(0,7) k;

INSERT INTO historico (id_matricula, n1, n2, n3, media_final, frequencia, situacao)
SELECT m.id_matricula, round((random()*10)::numeric,1), round((random()*10)::numeric,1),
       round((random()*10)::numeric,1), round((random()*10)::numeric,1),
       round((random()*100)::numeric,1), (ARRAY['x1','x2','x3'])[1+(m.id_matricula%3)]
FROM matricula m;

INSERT INTO log_matricula (id_matricula, acao, ocorrido_em, usuario, detalhe)
SELECT m.id_matricula, (ARRAY['INSERT','UPDATE'])[k],
       timestamp '2024-01-01' + random()*interval '700 days',
       'u'||(1+floor(random()*50)::int), 'registro sintetico'
FROM matricula m, generate_series(1,2) k;

INSERT INTO feriado (data, descricao)
SELECT date '2025-01-01' + g, 'Feriado '||g FROM generate_series(1,300) g;

INSERT INTO pais_feriado (fk_id_pais, fk_id_feriado)
SELECT 1+(g%5), g FROM generate_series(1,300) g
UNION ALL
SELECT 1+((g+1)%5), g FROM generate_series(1,300) g;

VACUUM ANALYZE;

\echo '### AMBIENTE'
SELECT version();
SELECT name, setting FROM pg_settings
 WHERE name IN ('shared_buffers','work_mem','effective_cache_size','random_page_cost',
                'max_parallel_workers_per_gather','jit') ORDER BY name;
SELECT relname, reltuples::bigint AS linhas, pg_size_pretty(pg_total_relation_size(oid)) AS tamanho
  FROM pg_class WHERE relnamespace='public'::regnamespace AND relkind='r'
   AND relname IN ('aluno','turma','matricula','historico','log_matricula') ORDER BY relname;

-- 10.2 Consultas avaliadas (uma por índice)
\set q1 'SELECT a.id_aluno, a.nome FROM matricula m JOIN aluno a ON a.id_aluno = m.id_aluno WHERE m.id_turma = 12345'
\set q2 'SELECT id_turma, codigo, turno FROM turma WHERE id_professor = 777 AND id_periodo_letivo = 5'
\set q3 'SELECT id_turma, codigo, id_professor FROM turma WHERE id_disciplina = 321 AND id_periodo_letivo = 5'
\set q4 'SELECT id_aluno, nome FROM aluno WHERE id_curriculo = 42'
\set q5 'SELECT acao, ocorrido_em, usuario FROM log_matricula WHERE id_matricula = 555555 ORDER BY ocorrido_em DESC'
\set q6 'SELECT id_curriculo, ano_vigencia FROM curriculo WHERE id_curso = 10 AND ativo'
\set q0 'SELECT d.codigo, h.media_final, h.situacao FROM matricula m JOIN historico h ON h.id_matricula = m.id_matricula JOIN turma t ON t.id_turma = m.id_turma JOIN disciplina d ON d.id_disciplina = t.id_disciplina WHERE m.id_aluno = 4321'

-- 10.3 Controle: histórico de um aluno — deve usar apenas índices já existentes
--      (uq_matricula_aluno_turma, uq_historico_matricula, PKs): nenhum índice novo.
\echo '### T0 CONTROLE'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q0;
\o
EXPLAIN (ANALYZE, BUFFERS) :q0;

-- ---------------------------------------------------------------------------
-- I1 idx_matricula_turma_aluno  | Q1: alunos da turma 12345
-- ---------------------------------------------------------------------------
\echo '### T1 ANTES'
BEGIN;
DROP INDEX idx_matricula_turma_aluno;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q1;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q1;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q1;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q1;
ROLLBACK;
\echo '### T1 DEPOIS'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q1;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q1;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q1;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q1;

-- ---------------------------------------------------------------------------
-- I2 idx_turma_professor_periodo | Q2
-- ---------------------------------------------------------------------------
\echo '### T2 ANTES'
BEGIN;
DROP INDEX idx_turma_professor_periodo;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q2;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q2;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q2;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q2;
ROLLBACK;
\echo '### T2 DEPOIS'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q2;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q2;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q2;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q2;

-- ---------------------------------------------------------------------------
-- I3 idx_turma_disciplina_periodo | Q3
-- ---------------------------------------------------------------------------
\echo '### T3 ANTES'
BEGIN;
DROP INDEX idx_turma_disciplina_periodo;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q3;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q3;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q3;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q3;
ROLLBACK;
\echo '### T3 DEPOIS'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q3;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q3;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q3;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q3;

-- ---------------------------------------------------------------------------
-- I4 idx_aluno_curriculo | Q4
-- ---------------------------------------------------------------------------
\echo '### T4 ANTES'
BEGIN;
DROP INDEX idx_aluno_curriculo;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q4;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q4;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q4;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q4;
ROLLBACK;
\echo '### T4 DEPOIS'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q4;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q4;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q4;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q4;

-- ---------------------------------------------------------------------------
-- I5 idx_log_matricula_matricula_ocorrido | Q5
-- ---------------------------------------------------------------------------
\echo '### T5 ANTES'
BEGIN;
DROP INDEX idx_log_matricula_matricula_ocorrido;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q5;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q5;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q5;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q5;
ROLLBACK;
\echo '### T5 DEPOIS'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q5;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q5;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q5;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q5;

-- ---------------------------------------------------------------------------
-- CANDIDATO PARCIAL (NÃO incluído na seção 8 — avaliado e descartado se não
-- trouxer ganho): curriculo (id_curso) WHERE ativo | Q6: currículos ativos do curso
-- Teste todo em transação revertida (ROLLBACK): o índice NÃO permanece.
-- ---------------------------------------------------------------------------
\echo '### T6 ANTES'
BEGIN;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q6;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q6;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q6;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q6;
CREATE INDEX idx_curriculo_curso_ativo ON curriculo (id_curso) WHERE ativo;
\echo '### T6 DEPOIS'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) :q6;
\o
\echo '## run 1'
EXPLAIN (ANALYZE, BUFFERS) :q6;
\echo '## run 2'
EXPLAIN (ANALYZE, BUFFERS) :q6;
\echo '## run 3'
EXPLAIN (ANALYZE, BUFFERS) :q6;
ROLLBACK;


-- ---------------------------------------------------------------------------
-- 10.4 CUSTO DE ESCRITA do índice I5 (tabela log_matricula, a mais escrita):
--      INSERT de 200.000 linhas sintéticas, sem e com o índice, 3 execuções
--      alternadas, cada uma em transação revertida (ROLLBACK).
-- ---------------------------------------------------------------------------
\set w1 'INSERT INTO log_matricula (id_matricula, acao, ocorrido_em, usuario, detalhe) SELECT 1+(g%800000), \'INSERT\', now()::timestamp, \'u1\', \'registro sintetico\' FROM generate_series(1,200000) g'
\echo '### T7 ANTES'
\echo '## run 1'
BEGIN; DROP INDEX idx_log_matricula_matricula_ocorrido; EXPLAIN (ANALYZE, BUFFERS) :w1; ROLLBACK;
\echo '## run 2'
BEGIN; DROP INDEX idx_log_matricula_matricula_ocorrido; EXPLAIN (ANALYZE, BUFFERS) :w1; ROLLBACK;
\echo '## run 3'
BEGIN; DROP INDEX idx_log_matricula_matricula_ocorrido; EXPLAIN (ANALYZE, BUFFERS) :w1; ROLLBACK;
\echo '### T7 DEPOIS'
\echo '## run 1'
BEGIN; EXPLAIN (ANALYZE, BUFFERS) :w1; ROLLBACK;
\echo '## run 2'
BEGIN; EXPLAIN (ANALYZE, BUFFERS) :w1; ROLLBACK;
\echo '## run 3'
BEGIN; EXPLAIN (ANALYZE, BUFFERS) :w1; ROLLBACK;

-- Tamanho dos índices criados (custo de armazenamento)
\echo '### TAMANHOS'
SELECT indexrelid::regclass AS indice, pg_size_pretty(pg_relation_size(indexrelid)) AS tamanho
  FROM pg_index WHERE indrelid IN ('matricula'::regclass,'turma'::regclass,'aluno'::regclass,'log_matricula'::regclass,'curriculo'::regclass)
 ORDER BY indrelid::regclass::text, 1::text;
SELECT relname, pg_size_pretty(pg_relation_size(oid)) AS tabela
  FROM pg_class WHERE relname IN ('matricula','turma','aluno','log_matricula') ORDER BY 1;


/* =============================================================================
   11. COMPARAÇÃO DOS RESULTADOS DE DESEMPENHO
   ============================================================================= */
-- RESULTADOS REAIS, medidos por execução deste mesmo script em
--   PostgreSQL 16.15 (Ubuntu), 1 vCPU, 4 GB RAM, shared_buffers=128MB,
--   work_mem=4MB, random_page_cost=4, max_parallel_workers_per_gather=2, jit=on,
--   dados SINTÉTICOS (aluno 100 mil, turma 60 mil, matricula 800 mil,
--   historico 800 mil, log_matricula 1,6 mi), cache aquecido (1 execução de
--   aquecimento descartada + 3 registradas; valor = MEDIANA das 3).
-- Tempos absolutos dependem do hardware; o que se transfere é a mudança de plano
-- e de buffers. Medições abaixo de ~0,05 ms têm resolução limitada: o ganho %
-- nesses casos é indicativo, não preciso.
-- Fórmula: Ganho(%) = (Antes - Depois) / Antes * 100  (negativo = regressão)
-- Nenhum valor abaixo é estimado: todos vêm de EXPLAIN (ANALYZE, BUFFERS) reais.

CREATE TEMP TABLE resultado_desempenho (
    teste          text, indice text, colunas text, consulta text,
    tempo_antes_ms numeric, tempo_depois_ms numeric,
    buffers_antes  integer, buffers_depois  integer,
    plano_antes    text,    plano_depois    text,
    decisao        text
);
INSERT INTO resultado_desempenho VALUES
  ('T1','idx_matricula_turma_aluno','matricula (id_turma, id_aluno)','Q1',57.029,0.028,5134,40,'Parallel Seq Scan em matricula (800 mil linhas) + Gather','Index Only Scan idx_matricula_turma_aluno (Heap Fetches: 0)','MANTER'),
  ('T2','idx_turma_professor_periodo','turma (id_professor, id_periodo_letivo)','Q2',2.914,0.01,442,4,'Seq Scan em turma (60 mil linhas)','Bitmap Index Scan + Bitmap Heap Scan','MANTER'),
  ('T3','idx_turma_disciplina_periodo','turma (id_disciplina, id_periodo_letivo)','Q3',2.692,0.01,442,6,'Seq Scan em turma (60 mil linhas)','Bitmap Index Scan + Bitmap Heap Scan','MANTER'),
  ('T4','idx_aluno_curriculo','aluno (id_curriculo)','Q4',5.039,0.449,1137,587,'Seq Scan em aluno (100 mil linhas)','Bitmap Index Scan + Bitmap Heap Scan','MANTER'),
  ('T5','idx_log_matricula_matricula_ocorrido','log_matricula (id_matricula, ocorrido_em)','Q5',102.747,0.006,16495,6,'Parallel Seq Scan em log_matricula (1,6 mi linhas) + Gather + Sort','Index Scan Backward (sem Sort)','MANTER (custo de escrita medido: ver W1)'),
  ('T6','idx_curriculo_curso_ativo (CANDIDATO PARCIAL, descartado)','curriculo (id_curso) WHERE ativo','Q6',0.008,0.008,1,1,'Seq Scan em curriculo (120 linhas)','Seq Scan em curriculo (índice NÃO usado pelo planner)','DESCARTADO (não usado; sem ganho)'),
  ('T7','idx_log_matricula_matricula_ocorrido (custo de escrita)','log_matricula (id_matricula, ocorrido_em)','W1',1400.676,1780.339,607417,1208959,'INSERT sem o índice','INSERT com o índice','Custo aceito pelo ganho de 5 (leitura)');

SELECT teste, indice,
       tempo_antes_ms, tempo_depois_ms,
       round(tempo_antes_ms - tempo_depois_ms, 3)                          AS diferenca_ms,
       round((tempo_antes_ms - tempo_depois_ms) / tempo_antes_ms * 100, 2) AS ganho_pct,
       buffers_antes, buffers_depois,
       plano_antes, plano_depois, decisao
FROM resultado_desempenho ORDER BY teste;

